# Site settings
title: Bernhard Rieder
description: >- # this means to ignore newlines until "baseurl:"
  Hi there, my name is <b>Bernhard Rieder</b> and I'm a tech enthusiast as well as a passionate game programmer who currently works for Ubisoft Bucharest.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://bernhardrieder.dev" # the base hostname & protocol for your site, e.g. http://example.com
# repository: bernhardrieder


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Bernhard Rieder
  image    : "/assets/img/me_face.jpg"
  email    : contact@bernhardrieder.dev
  github   : bernhardrieder
  twitter  : bernhard_rieder
  linkedin : bernhard-rieder
  facebook : rieder.bernhard


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name
  portfolio:
    output: true
    permalink: /portfolio/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "page"

# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock

timezone: Europe/Vienna