# Site settings
title: Walter Bolitto Carvalho
description: >- # this means to ignore newlines until "baseurl:"
  Edtech / Jogos sérios / Cultura Maker
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://bolitto.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# repository: bernhardrieder


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Walter Bolitto Carvalho
  image    : "/assets/img/me_face.jpg"
  email    : bolitto.walter@gmail.com
  github   : Bolitto
  twitter  : 
  linkedin : walter-bolitto-carvalho-851290120
  facebook : 


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock

timezone: Europe/Vienna
